### ISSUE TITLE
Files showing "null" only

### ISSUE THREAD

**Issue by smallminddesign** [Nicolab/atom-local-history#53]
Any type of file I open from about the past month is showing me "null" and is 1KB in size. I tried to uninstall and reinstall, but same issue. Please help!

![image](https://user-images.githubusercontent.com/12736796/30460680-540c9cd6-9986-11e7-9da2-48201204cd5d.png)

**Comment by Nicolab** [comment]
Heloo,

Please:
* Atom version?
* Any logs in the console (dev tools)?

**Comment by smallminddesign** [comment]
v1.20.1 x64 - and up to date apparently.

Sorry, but how do I show you the logs from the console? I am actually running Atom on Win10 now and having the same issue as I was on my Win7 computer. How can this be? :|

I attached my local-history configuration settings - maybe I'm missing something obvious there.

![image](https://user-images.githubusercontent.com/12736796/30762013-42a30880-9fae-11e7-9648-9e2682beddae.png)

**Comment by Nicolab** [comment]
Thanks.
Just to try, please removes the space in the folder name of the storage path. Restart Atom (close and open) and check the history

> Sorry, but how do I show you the logs from the console?

Ctrl + Maj + i

or by the menu: View -> Developer > Toggle Developer Tools

**Comment by AlexisBGD** [comment]
Hello
I've got the same problem. All my backuped files are 4 octets large with "null" inside
My dev console log is empty, no warning
It seems that buffer.cache is "null"

Atom version 1.21.0
Mac OS X Sierra
History folder without white space or strange characters

**Comment by AlexisBGD** [comment]
I found a new behaviour : when I install the pigments package the files are correctly backuped

To reproduce : 

1)  I deactivate "pigments" and files are "null" again
2)  I activate "pigments" and files are OK

It seems that the bug is related with the buffer.cache is emptyed in one case and not in the other case.

Perhaps you should change the way you backup the file and made a copy of the file directly from path to path before the save process without using the buffer cache. I'm not sure of what your code do exactly so my suggestion may be not a pertinent one...

**Comment by Nicolab** [comment]
Hello,


Subtil bug, good catch!
Thank you for the details and to have taken the time to look.

I will fix it as soon as possible.

**Comment by Nicolab** [comment]
Fixed in the v4.3.1.
Please, confirm that it's ok?

**Comment by AlexisBGD** [comment]
It seems to work well now

Thanks a lot

**Comment by Nicolab** [comment]
Great.
Thank you
